In [1]:
import pandas as pd

In [2]:
in_time_fe = pd.read_csv('../data/output/fe/out_of_time_fe.csv')
out_time_fe = pd.read_csv('../data/output/fe/out_of_time_fe.csv')

In [3]:
in_time_fe

,Unnamed: 0,Customer_id,No_dependants,Time_in_address,Time_in_current_job,Credit_cards,Debit_cards,Active_accounts,Active_loans,Active_mortgages,...,Financial_stability_index_H0_H12,Overdue_aggregation_H0_H3,Overdue_aggregation_H0_H6,Overdue_aggregation_H0_H12,Avg_inc_transactions_H0_H3,Avg_inc_transactions_H0_H6,Avg_inc_transactions_H0_H12,Avg_out_transactions_H0_H3,Avg_out_transactions_H0_H6,Avg_out_transactions_H0_H12
0,0,31264719,3,9.93,1.39,0,3,1,1,0.0,...,13.264733,0.00,0.00,0.0,133.600000,724.795000,602.736667,8.461781,-47.192220,-9.443633
1,1,33263992,1,9.54,5.97,0,2,3,1,0.0,...,0.794329,0.00,0.00,0.0,41.650000,48.865000,917.340000,-4.440045,-2.544932,2.922096
2,2,31153663,1,11.41,5.02,0,1,2,1,0.0,...,2.045454,0.00,-682.74,0.0,1562.720000,-59.180000,-69.130000,6.157080,-123.078796,-16.580449
3,3,34161420,1,3.42,4.40,0,1,2,1,0.0,...,-0.166373,0.00,-603.97,0.0,61.155000,848.115000,79.665000,0.081452,-51.611667,-5.362272
4,4,33407849,2,25.98,3.63,0,2,1,1,0.0,...,-10.119431,0.00,0.00,0.0,-910.707500,393.558500,-938.012500,55.401482,82.834391,67.912680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156865,159995,34145361,1,16.50,0.25,0,1,1,1,0.0,...,-0.282052,0.00,0.00,0.0,1131.068333,16.776667,-678.766667,-31.002370,-38.747504,-39.934330
156866,159996,37691952,0,2.81,1.58,0,2,1,1,0.0,...,0.512821,-233.98,0.00,0.0,33.243333,-804.810000,-1012.695000,7.588135,17.069643,-15.422440
156867,159997,35630042,0,11.25,6.95,1,1,3,1,0.0,...,-1.319598,0.00,-426.51,0.0,2176.090000,1408.835000,-508.480000,16.105702,-29.008191,-26.524499
156868,159998,32549616,1,10.52,1.00,0,1,1,1,0.0,...,-8.989519,-265.96,0.00,0.0,880.116667,1644.903333,824.043333,8.131690,0.619957,-0.205762
156869,159999,38303999,1,5.48,6.89,1,2,1,1,1.0,...,-3.594754,0.00,0.00,0.0,-4614.855000,2784.001000,1542.661667,-5.885417,83.904830,75.154390

In [5]:
out_time_fe

,Unnamed: 0,Customer_id,No_dependants,Time_in_address,Time_in_current_job,Credit_cards,Debit_cards,Active_accounts,Active_loans,Active_mortgages,...,Financial_stability_index_H0_H12,Overdue_aggregation_H0_H3,Overdue_aggregation_H0_H6,Overdue_aggregation_H0_H12,Avg_inc_transactions_H0_H3,Avg_inc_transactions_H0_H6,Avg_inc_transactions_H0_H12,Avg_out_transactions_H0_H3,Avg_out_transactions_H0_H6,Avg_out_transactions_H0_H12
0,0,31264719,3,9.93,1.39,0,3,1,1,0.0,...,13.264733,0.00,0.00,0.0,133.600000,724.795000,602.736667,8.461781,-47.192220,-9.443633
1,1,33263992,1,9.54,5.97,0,2,3,1,0.0,...,0.794329,0.00,0.00,0.0,41.650000,48.865000,917.340000,-4.440045,-2.544932,2.922096
2,2,31153663,1,11.41,5.02,0,1,2,1,0.0,...,2.045454,0.00,-682.74,0.0,1562.720000,-59.180000,-69.130000,6.157080,-123.078796,-16.580449
3,3,34161420,1,3.42,4.40,0,1,2,1,0.0,...,-0.166373,0.00,-603.97,0.0,61.155000,848.115000,79.665000,0.081452,-51.611667,-5.362272
4,4,33407849,2,25.98,3.63,0,2,1,1,0.0,...,-10.119431,0.00,0.00,0.0,-910.707500,393.558500,-938.012500,55.401482,82.834391,67.912680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156865,159995,34145361,1,16.50,0.25,0,1,1,1,0.0,...,-0.282052,0.00,0.00,0.0,1131.068333,16.776667,-678.766667,-31.002370,-38.747504,-39.934330
156866,159996,37691952,0,2.81,1.58,0,2,1,1,0.0,...,0.512821,-233.98,0.00,0.0,33.243333,-804.810000,-1012.695000,7.588135,17.069643,-15.422440
156867,159997,35630042,0,11.25,6.95,1,1,3,1,0.0,...,-1.319598,0.00,-426.51,0.0,2176.090000,1408.835000,-508.480000,16.105702,-29.008191,-26.524499
156868,159998,32549616,1,10.52,1.00,0,1,1,1,0.0,...,-8.989519,-265.96,0.00,0.0,880.116667,1644.903333,824.043333,8.131690,0.619957,-0.205762
156869,159999,38303999,1,5.48,6.89,1,2,1,1,1.0,...,-3.594754,0.00,0.00,0.0,-4614.855000,2784.001000,1542.661667,-5.885417,83.904830,75.154390